packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true
  protobufjs: true
  workerd: true

catalogs:
  default:
    "@types/node": ^25.9.7
    oxfmt: ^0.47.0
    oxlint: 1.78.0
    typescript: ^6.0.3

minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260918.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260918.1'
  - '@cloudflare/workerd-linux-64@1.20260918.1'
  - '@cloudflare/workerd-linux-arm64@1.20260918.1'
  - '@cloudflare/workerd-windows-64@1.20260918.1'
  - miniflare@5.20260918.0-alpha
  - workerd@1.20260918.1
  - wrangler@4.135.0
