taskOptions:
  envFile: true

tasks:
  fmt:
    command: "oxfmt --no-error-on-unmatched-pattern"
  fmt/check:
    extends: "fmt"
    args: "--check"
  lint:
    command: "oxlint --no-error-on-unmatched-pattern"
  lint/fix:
    extends: "lint"
    args: "--fix"
