name: Validate

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Lint and format check
        run: pnpm biome ci
      - name: Build all packages
        run: pnpm build
